// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQXItBaqdJhVj4bL7v72m6PtF-ylh0aB8',
    appId: '1:954332705767:web:24de0a7d7f9c0f56a24342',
    messagingSenderId: '954332705767',
    projectId: 'todo-clean-arch2024',
    authDomain: 'todo-clean-arch2024.firebaseapp.com',
    storageBucket: 'todo-clean-arch2024.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo_wzPd0_1zWd_xYZoWcQMoGnHbdVYVXc',
    appId: '1:954332705767:android:663c9262eda9a679a24342',
    messagingSenderId: '954332705767',
    projectId: 'todo-clean-arch2024',
    storageBucket: 'todo-clean-arch2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJdwTm0dwGH_plZRzJiOlrobI3TjlqNmY',
    appId: '1:954332705767:ios:bec40dd6965c2641a24342',
    messagingSenderId: '954332705767',
    projectId: 'todo-clean-arch2024',
    storageBucket: 'todo-clean-arch2024.appspot.com',
    iosBundleId: 'com.example.todoClearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJdwTm0dwGH_plZRzJiOlrobI3TjlqNmY',
    appId: '1:954332705767:ios:bec40dd6965c2641a24342',
    messagingSenderId: '954332705767',
    projectId: 'todo-clean-arch2024',
    storageBucket: 'todo-clean-arch2024.appspot.com',
    iosBundleId: 'com.example.todoClearn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQXItBaqdJhVj4bL7v72m6PtF-ylh0aB8',
    appId: '1:954332705767:web:39d0832a42adf942a24342',
    messagingSenderId: '954332705767',
    projectId: 'todo-clean-arch2024',
    authDomain: 'todo-clean-arch2024.firebaseapp.com',
    storageBucket: 'todo-clean-arch2024.appspot.com',
  );
}
